# awx_project/playbook.yml
- hosts: all
  tasks:
    - name: Ensure the Apache2 service is enabled and running
      ansible.builtin.service:
        name: apache2
        enabled: yes
        state: started
