# awx_project/playbook.yml
- hosts: all
  collections:
    - community.general
  tasks:
    - name: Ensure the NTP service is enabled and running
      ansible.builtin.systemd_service:
        name: ntp
        state: started
        enabled: yes
