# awx_project/playbook.yml
- hosts: wsl
  tasks:
    - name: Ensure the Apache HTTP Server is enabled and running
      ansible.builtin.service:
        name: apache-htcacheclean  # Replace with the actual service name on your system
        enabled: yes
        state: started
