# awx_project/playbook.yml
- hosts: all
  collections:
    - community.general
  tasks:
    - name: Ensure the NTP service is enabled and running
      systemd:
        name: ntp.service
        state: started
        enabled: yes
