# awx_project/playbook.yml
- hosts: all
  collections:
    - community.general
  tasks:
    - name: Ensure the NTP service is enabled and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
