# Example for systems using init instead of systemd
- hosts: all
  tasks:
    - name: Ensure the NTP service is enabled and running
      ansible.builtin.service:
        name: ntp
        enabled: yes
        state: started
